# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore picow-cgm-server.sln
    
    - name: Build
      run: dotnet build  picow-cgm-server.sln --no-restore
      
    - name: Publish
      run: dotnet publish --configuration Release --no-restore --self-contained true --output ./publish
          
    - name: Copy to Raspberry Pi
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.RASPBERRY_PI_IP }}
        username: ${{ secrets.RASPBERRY_PI_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./publish/"
        target: "/cgmserver"

    - name: Set permission and Run the application on Raspberry Pi
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RASPBERRY_PI_IP }}
        username: ${{ secrets.RASPBERRY_PI_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          chmod +x /cgmserver/yourapp
          /cgmserver/yourapp
          
